[[redirects]]
  from = "/manifest.json"
  to = "/public/manifest.json"
  status = 200

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[plugins.inputs.schedule]]
  function = "sendReminders"
  expression = "*/1 * * * *"





